### ISSUE TITLE
Error while running npm install

### ISSUE THREAD

**Issue by santhisenan** [ccfcet/karma#13]
$ npm install

> Karma@1.0.0-alpha-1 preinstall /Users/santhisenan/Projects/karma/src
> rm -rf ./node_modules/_

> Karma@1.0.0-alpha-1 postinstall /Users/santhisenan/Projects/karma/src
> ./link-modules.sh

npm WARN data@1.0.0-alpha-1 No repository field.

audited 60 packages in 4.853s
found 0 vulnerabilities

> argon2@0.19.3 install /Users/santhisenan/Projects/karma/src/lib/authentication/node_modules/argon2
> node-gyp rebuild

  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  LIBTOOL-STATIC Release/argon2.a
Failed to import the site module
Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!
     PYTHONPATH is currently: "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib"
     You should `unset PYTHONPATH` to fix this.
make: *** [Release/argon2.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/santhisenan/Projects/karma/src/lib/authentication/node_modules/argon2
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN authentication@1.0.0-alpha-1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.19.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/santhisenan/.npm/_logs/2018-06-07T12_41_55_182Z-debug.log
audited 1804 packages in 73.871s
found 9 vulnerabilities (5 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by jilvin** [comment]
@santhisenan I think this issue has been fixed already. If not we can reopen.
