### ISSUE TITLE
Removing value column from Student attendance

### ISSUE THREAD

**Issue by rabeehrz** [ccfcet/karma#61]
I don't think there is a need for the value column in student attendance (Assuming it to be either 0 or 1).
We can just store the student who gets attendance for a particular course.

I think this would be better in the long term.

**Comment by rabeehrz** [comment]
@jacob13400 @ebby21

**Comment by jilvin** [comment]
I don't remember exactly why we added. Make sure edge cases are covered in
the system before removing. For instance, case where all students are
absent. I am just sharing my thoughts. Keep up the work.
